// <auto-generated />
using System;
using Mediateca.Infrastructure.EfCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Mediateca.Infractructure.EfCore.Migrations
{
    [DbContext(typeof(MediatecaDbContext))]
    [Migration("20250317174903_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Mediateca.Domain.Model.Album", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("MusicianId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int?>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MusicianId");

                    b.ToTable("Albums", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MusicianId = 1,
                            Name = "Imagine",
                            Year = 1971
                        },
                        new
                        {
                            Id = 2,
                            MusicianId = 1,
                            Name = "Double Fantasy",
                            Year = 1980
                        },
                        new
                        {
                            Id = 3,
                            MusicianId = 2,
                            Name = "A Night at the Opera",
                            Year = 1975
                        },
                        new
                        {
                            Id = 4,
                            MusicianId = 2,
                            Name = "The Game",
                            Year = 1980
                        },
                        new
                        {
                            Id = 5,
                            MusicianId = 3,
                            Name = "The Rise and Fall of Ziggy Stardust",
                            Year = 1972
                        },
                        new
                        {
                            Id = 6,
                            MusicianId = 3,
                            Name = "Heroes",
                            Year = 1977
                        },
                        new
                        {
                            Id = 7,
                            MusicianId = 4,
                            Name = "Back to Black",
                            Year = 2006
                        },
                        new
                        {
                            Id = 8,
                            MusicianId = 4,
                            Name = "Frank",
                            Year = 2003
                        },
                        new
                        {
                            Id = 9,
                            MusicianId = 5,
                            Name = "Nevermind",
                            Year = 1991
                        },
                        new
                        {
                            Id = 10,
                            MusicianId = 5,
                            Name = "In Utero",
                            Year = 1993
                        },
                        new
                        {
                            Id = 11,
                            MusicianId = 6,
                            Name = "Thriller",
                            Year = 1982
                        },
                        new
                        {
                            Id = 12,
                            MusicianId = 6,
                            Name = "Bad",
                            Year = 1987
                        },
                        new
                        {
                            Id = 13,
                            MusicianId = 7,
                            Name = "Elvis Presley",
                            Year = 1956
                        },
                        new
                        {
                            Id = 14,
                            MusicianId = 7,
                            Name = "From Elvis in Memphis",
                            Year = 1969
                        },
                        new
                        {
                            Id = 15,
                            MusicianId = 8,
                            Name = "Like a Virgin",
                            Year = 1984
                        },
                        new
                        {
                            Id = 16,
                            MusicianId = 8,
                            Name = "Ray of Light",
                            Year = 1998
                        },
                        new
                        {
                            Id = 17,
                            MusicianId = 9,
                            Name = "Exodus",
                            Year = 1977
                        },
                        new
                        {
                            Id = 18,
                            MusicianId = 9,
                            Name = "Legend",
                            Year = 1984
                        },
                        new
                        {
                            Id = 19,
                            MusicianId = 10,
                            Name = "21",
                            Year = 2011
                        },
                        new
                        {
                            Id = 20,
                            MusicianId = 10,
                            Name = "25",
                            Year = 2015
                        });
                });

            modelBuilder.Entity("Mediateca.Domain.Model.Musician", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Musicians", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Член группы Beatles.",
                            Name = "John Lennon"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Вокалист Queen.",
                            Name = "Freddie Mercury"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Легендарный рок-музыкант.",
                            Name = "David Bowie"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Джазовая певица.",
                            Name = "Amy Winehouse"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Вокалист Nirvana.",
                            Name = "Kurt Cobain"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Король Поп-музыки.",
                            Name = "Michael Jackson"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Король Рок-н-Ролла.",
                            Name = "Elvis Presley"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Королева Поп-музыки.",
                            Name = "Madonna"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Легенда рэгги.",
                            Name = "Bob Marley"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Одна из известнейших певиц Великобритании.",
                            Name = "Adele"
                        });
                });

            modelBuilder.Entity("Mediateca.Domain.Model.Track", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AlbumId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Time")
                        .HasColumnType("text");

                    b.Property<int?>("TrackNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AlbumId");

                    b.ToTable("Tracks", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AlbumId = 1,
                            Name = "Imagine",
                            Time = "3:03",
                            TrackNumber = 1
                        },
                        new
                        {
                            Id = 2,
                            AlbumId = 1,
                            Name = "Jealous Guy",
                            Time = "4:14",
                            TrackNumber = 2
                        },
                        new
                        {
                            Id = 3,
                            AlbumId = 2,
                            Name = "Watching the Wheels",
                            Time = "3:30",
                            TrackNumber = 3
                        },
                        new
                        {
                            Id = 4,
                            AlbumId = 2,
                            Name = "Beautiful Boy",
                            Time = "4:05",
                            TrackNumber = 4
                        },
                        new
                        {
                            Id = 5,
                            AlbumId = 3,
                            Name = "Bohemian Rhapsody",
                            Time = "5:55",
                            TrackNumber = 1
                        },
                        new
                        {
                            Id = 6,
                            AlbumId = 3,
                            Name = "You're My Best Friend",
                            Time = "2:52",
                            TrackNumber = 2
                        },
                        new
                        {
                            Id = 7,
                            AlbumId = 4,
                            Name = "Another One Bites the Dust",
                            Time = "3:35",
                            TrackNumber = 1
                        },
                        new
                        {
                            Id = 8,
                            AlbumId = 4,
                            Name = "Crazy Little Thing Called Love",
                            Time = "2:43",
                            TrackNumber = 2
                        },
                        new
                        {
                            Id = 9,
                            AlbumId = 5,
                            Name = "Starman",
                            Time = "4:16",
                            TrackNumber = 1
                        },
                        new
                        {
                            Id = 10,
                            AlbumId = 5,
                            Name = "Ziggy Stardust",
                            Time = "3:13",
                            TrackNumber = 2
                        },
                        new
                        {
                            Id = 11,
                            AlbumId = 6,
                            Name = "Heroes",
                            Time = "6:07",
                            TrackNumber = 1
                        },
                        new
                        {
                            Id = 12,
                            AlbumId = 6,
                            Name = "Beauty and the Beast",
                            Time = "3:32",
                            TrackNumber = 2
                        },
                        new
                        {
                            Id = 13,
                            AlbumId = 7,
                            Name = "Rehab",
                            Time = "3:34",
                            TrackNumber = 1
                        },
                        new
                        {
                            Id = 14,
                            AlbumId = 7,
                            Name = "You Know I'm No Good",
                            Time = "4:17",
                            TrackNumber = 2
                        },
                        new
                        {
                            Id = 15,
                            AlbumId = 8,
                            Name = "Stronger Than Me",
                            Time = "3:33",
                            TrackNumber = 1
                        },
                        new
                        {
                            Id = 16,
                            AlbumId = 8,
                            Name = "Take the Box",
                            Time = "3:20",
                            TrackNumber = 2
                        },
                        new
                        {
                            Id = 17,
                            AlbumId = 9,
                            Name = "Smells Like Teen Spirit",
                            Time = "5:01",
                            TrackNumber = 1
                        },
                        new
                        {
                            Id = 18,
                            AlbumId = 9,
                            Name = "Come as You Are",
                            Time = "3:39",
                            TrackNumber = 2
                        },
                        new
                        {
                            Id = 19,
                            AlbumId = 10,
                            Name = "Heart-Shaped Box",
                            Time = "4:41",
                            TrackNumber = 1
                        },
                        new
                        {
                            Id = 20,
                            AlbumId = 10,
                            Name = "Rape Me",
                            Time = "2:50",
                            TrackNumber = 2
                        });
                });

            modelBuilder.Entity("Mediateca.Domain.Model.Album", b =>
                {
                    b.HasOne("Mediateca.Domain.Model.Musician", "Musician")
                        .WithMany("Albums")
                        .HasForeignKey("MusicianId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Musician");
                });

            modelBuilder.Entity("Mediateca.Domain.Model.Track", b =>
                {
                    b.HasOne("Mediateca.Domain.Model.Album", "Album")
                        .WithMany("Tracks")
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Album");
                });

            modelBuilder.Entity("Mediateca.Domain.Model.Album", b =>
                {
                    b.Navigation("Tracks");
                });

            modelBuilder.Entity("Mediateca.Domain.Model.Musician", b =>
                {
                    b.Navigation("Albums");
                });
#pragma warning restore 612, 618
        }
    }
}
